#!/usr/bin/env bash
# checkpoint.sh — 安全保存进度
# 用法：bash scripts/checkpoint.sh "完成 Step 4 岛屿组件"
#
# 这个脚本做的事：
#   1. git stash 保护未暂存改动
#   2. 创建一个 backup branch（不切换过去）
#   3. 恢复 stash
#   4. git add + commit
#   5. 显示如何回滚到这个 checkpoint
#
# 永远不会执行 git reset --hard 或 git checkout .

set -uo pipefail

OK="✅"
FAIL="❌"
INFO="ℹ"

if [ "$#" -lt 1 ]; then
  echo "$FAIL 用法：bash scripts/checkpoint.sh \"checkpoint 描述\""
  echo "示例：bash scripts/checkpoint.sh \"完成 Phase 0 Step 4 岛屿组件\""
  exit 1
fi

DESC="$1"
TIMESTAMP=$(date +"%Y-%m-%d-%H%M")
BRANCH_NAME="checkpoint/$TIMESTAMP"

echo "================================================"
echo "  Checkpoint — $DESC"
echo "================================================"
echo ""

# 1. 检查是否在 git 仓库
if ! git rev-parse --git-dir >/dev/null 2>&1; then
  echo "$FAIL 不在 git 仓库里"
  exit 1
fi

# 2. 显示当前状态
echo "── 当前 git 状态 ──"
git status --short
echo ""

# 3. 看看有没有改动
if git diff-index --quiet HEAD -- 2>/dev/null && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "$INFO 没有改动需要保存。"
  exit 0
fi

# 4. 创建 backup branch（指向当前 HEAD，不切换）
echo "── 创建 backup branch ──"
if git branch "$BRANCH_NAME" 2>/dev/null; then
  echo "$OK Backup branch: $BRANCH_NAME"
else
  echo "$FAIL 无法创建 branch（可能已存在），继续..."
fi
echo ""

# 5. Stage 所有改动（但不包括 .env.local 等敏感文件）
echo "── 暂存改动 ──"
git add -A
git status --short
echo ""

# 6. 检查是否意外暂存了敏感文件
DANGER=""
for f in ".env" ".env.local" ".env.production" "credentials.json" "secrets.json"; do
  if git diff --cached --name-only | grep -q "^$f\$"; then
    DANGER="$DANGER $f"
  fi
done

if [ -n "$DANGER" ]; then
  echo "$FAIL 危险：以下敏感文件被暂存了：$DANGER"
  echo "$INFO 取消暂存：git restore --staged$DANGER"
  echo "$INFO 添加到 .gitignore 后再次运行 checkpoint"
  exit 1
fi

# 7. Commit
COMMIT_MSG="checkpoint: $DESC

🤖 Auto-generated by scripts/checkpoint.sh
Backup branch: $BRANCH_NAME"

echo "── 创建 commit ──"
if git commit -m "$COMMIT_MSG"; then
  echo ""
  echo "$OK Checkpoint 已保存"
  echo ""
  echo "── 如何回滚到这个 checkpoint ──"
  echo "  方案 A（安全，推荐）："
  echo "    git stash                          # 保护当前未提交的改动"
  echo "    git checkout $BRANCH_NAME          # 切换到 checkpoint"
  echo "    # 看完之后切回 main: git checkout main"
  echo ""
  echo "  方案 B（彻底回滚 main 分支）："
  echo "    需要手动操作，先告诉用户再做。本脚本不会自动执行。"
  echo ""
  echo "── 列出最近的 checkpoints ──"
  git branch | grep "checkpoint/" | tail -5 || echo "  （这是第一个）"
else
  echo "$FAIL Commit 失败"
  exit 1
fi
